- name: Create folder directory for savedsearches
  file:
    path: "{{ item }}"
    state: directory
    owner: splunk
    group: splunk
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/timestamp_app/local/

- name: copy savedsearches.conf to splunk server
  copy:
    src: savedsearches.conf
    dest: /opt/splunk/etc/apps/timestamp_app/local/savedsearches.conf
    owner: splunk
    group: splunk
  notify: restart splunk