- name: copy savedsearches.conf to splunk server
  copy:
    src: timestamp_app
    dest: /opt/splunk/etc/apps/
    owner: splunk
    group: splunk
  register: app_copy
 
- name: restart splunk
  service: name=splunk state=restarted
  when: app_copy.changed
  become: yes

- name: Run Collect search
  uri:
    url: "https://127.0.0.1:8089/servicesNS/admin/search/search/jobs"
    method: POST
    body_format: form-urlencoded
    user: "admin"
    password: "{{ splunk_admin_password }}"
    validate_certs: false
    body:
      search: "| savedsearch bots_collect_to_hec_file time=\"2021-03-09 09:00\""
    timeout: 90
    return_content: yes
    status_code: 201
     
- name: checking if collect search is done
  wait_for: 
    path: /tmp/heccollect.stash_hec
    timeout: 2800
    sleep: 10

- name: Run HEC push
  shell: /opt/splunk/etc/apps/timestamp_app/bin/hec_push.py 
