- name: copy savedsearches.conf to splunk server
  copy:
    src: timestamp_app
    dest: /opt/splunk/etc/apps/
    owner: splunk
    group: splunk
  notify: restart splunk

- name: Run Collect search
  uri:
    url: "https://127.0.0.1:8089/servicesNS/admin/search/search/jobs/export"
    method: POST
    user: "admin"
    password: "{{ splunk_admin_password }}"
    validate_certs: false
    body: "-d search=" \| savedsearch bots_collect_to_hec_file time="{{ ansible_date_time.date }} 09:00""
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: [ 200, 201 ]
    timeout: 90
 
- name: checking if collect search is done
  stat: path=/tmp/heccollect.stash_hec
  register: hec_collect

- name: is splunk installed?
  debug: msg='HEC collect is done running'
  when: hec_collect.stat.exists

- name: Run HEC push
  script: /opt/splunk/etc/apps/timestamp_app/bin/hec_push.py 
  args: 
    executable: python3 
  when: splunk_path.stat.exists == true