- name: Create local folder directory
  file:
    path: "{{ item }}"
    state: directory
    owner: splunk
    group: splunk
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/Splunk_SA_CIM/local/

- name: copy macros.conf to splunk server
  copy:
    src: macros_cim.conf
    dest: /opt/splunk/etc/apps/Splunk_SA_CIM/local/macros.conf
    owner: splunk
    group: splunk
  notify: restart splunk