
- name: Create folder directory for inputs configuration
  file:
    path: /opt/splunk/etc/apps/splunk_httpinput/local
    state: directory
    owner: splunk
    group: splunk
    recurse: yes

- name: copy hec_inputs.conf
  copy:
    src: hec_inputs.conf
    dest: /opt/splunk/etc/apps/splunk_httpinput/local/inputs.conf
    owner: splunk
    group: splunk
  notify: restart splunk
