---
# This playbook contains common tasks in this role

- include: splunk.yml
- include: configure_inputs.yml
- include: configure_hecinputs.yml
- include: configure_indexes.yml
- include: configure_limits.yml
- include: configure_web_conf.yml
- include: configure_server_conf.yml
#- include: configure_props.yml
- include: create_serverclass.yml
- include: install_enterprise_security.yml
- include: install_botsv1_dataset.yml
  when: splunk_bots_dataset is regex("(1)(?!a)")
- include: install_botsv1a_dataset.yml
  when: splunk_bots_dataset is regex("1a")
- include: install_botsv2_dataset.yml
  when: splunk_bots_dataset is regex("(2)(?!a)")
- include: install_botsv2a_dataset.yml
  when: splunk_bots_dataset is regex("2a")
- include: install_botsv3_dataset.yml
  when: splunk_bots_dataset is regex("3")
- include: configure_timestamp.yml
- include: install_app_from_umbrio_s3.yml
  with_items:
    - "{{ cim_vladiator }}"
    - "{{ amazon_guardduty_ta }}"
    - "{{ cisco_anyconnect_ta }}"
    - "{{ code24_ta }}"
    - "{{ decrypy_ta }}"
    - "{{ ms_azure_ta }}"
    - "{{ osquery_ta }}"
    - "{{ splunk_cisco_ta }}"
    - "{{ splunk_ms_cloud_ta }}"
    - "{{ splunk_symantec_ep_ta }}"
    - "{{ splunk_tenable_ta }}"
    - "{{ splunk_linux_ta }}"
    - "{{ code24_ta }}"
    - "{{ url_toolbox }}"
    - "{{ virustotal_workflow_ta }}"
- include: install_app_from_s3.yml
  with_items:
    - "{{ splunk_windows_ta }}"
    - "{{ timeline_custom_visualization }}"
    - "{{ splunk_asx_app }}"
    - "{{ status_indicator_custom_visualization }}"
    - "{{ punchard_custom_visualization }}"
    - "{{ splunk_attack_range_dashboard }}"
    - "{{ splunk_cim_app }}"
    - "{{ splunk_escu_app }}"
    - "{{ splunk_python_app }}"
    - "{{ splunk_mltk_app }}"
    - "{{ splunk_security_essentials_app }}"
    - "{{ splunk_sysmon_ta }}"
    - "{{ splunk_aws_ta }}"
    - "{{ splunk_office_365_ta }}"
    - "{{ splunk_kinesis_ta }}"
- include: configure_attack_range_dashboard.yml
- include: configure_escu.yml
- include: install_stream_app.yml
